version: '3.8'

services:
  rag-app:
    build: .
    container_name: rag-system
    ports:
      - "7860:7860"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./logs:/app/logs
      - ./huggingface_cache:/app/.cache/huggingface
      - ./uploads:/app/uploads
    env_file:
      - .env
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  
      - PYTHONUNBUFFERED=1
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - HF_HOME=/app/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import socket; socket.create_connection(('localhost', 7860), timeout=2)\""]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s